---
version: '3'
services:
  notlar-db:
    image: postgres:13
    container_name: notlar_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./ansible/roles/notlar_setup/files/bbdd/notlar.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data

  notlar-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notlar_app
    expose:
      - "5000"
    depends_on:
      - notlar-db
    env_file:
      - .env
    volumes:
      - ./notlar:/app/notlar
    command: gunicorn -w 4 -b 0.0.0.0:5000 notlar.wsgi:app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - notlar-app

volumes:
  postgres_data:
