---
- name: Install packages required by Notlar
  become: true
  ansible.builtin.package:
    name: "{{ notlar_dependency_packages }}"
    state: present

- name: Install Python modules required by Notlar
  become: true
  ansible.builtin.pip:
    name: "{{ notlar_dependency_python_modules }}"
    state: present
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
